-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 21:19:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livros` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `isbn` VARCHAR(17) NULL,
  `edicao` VARCHAR(45) NULL,
  `editora` VARCHAR(100) NULL,
  `ano_publicacao` YEAR NULL,
  `preco` FLOAT NULL,
  `categoria` VARCHAR(50) NULL,
  PRIMARY KEY (`id_livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autores` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `biografia` LONGTEXT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compras` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `livro_comprado` INT NOT NULL,
  `quantidade` INT NULL,
  `data_compra` DATETIME NULL,
  PRIMARY KEY (`id_compra`, `livro_comprado`),
  INDEX `fk_Compras_Livros1_idx` (`livro_comprado` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Livros1`
    FOREIGN KEY (`livro_comprado`)
    REFERENCES `mydb`.`Livros` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendas` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `livro_vendido` INT NOT NULL,
  `quantidade` INT NULL,
  `data_venda` DATETIME NULL,
  PRIMARY KEY (`id_venda`, `livro_vendido`),
  INDEX `fk_Vendas_Livros1_idx` (`livro_vendido` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_Livros1`
    FOREIGN KEY (`livro_vendido`)
    REFERENCES `mydb`.`Livros` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LivrosAutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LivrosAutores` (
  `Livros_id_livro` INT NOT NULL,
  `Autores_id_autor` INT NOT NULL,
  PRIMARY KEY (`Livros_id_livro`, `Autores_id_autor`),
  INDEX `fk_Livros_has_Autores_Autores1_idx` (`Autores_id_autor` ASC) VISIBLE,
  INDEX `fk_Livros_has_Autores_Livros_idx` (`Livros_id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_Livros_has_Autores_Livros`
    FOREIGN KEY (`Livros_id_livro`)
    REFERENCES `mydb`.`Livros` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livros_has_Autores_Autores1`
    FOREIGN KEY (`Autores_id_autor`)
    REFERENCES `mydb`.`Autores` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
