# Generated by Django 4.2.19 on 2025-02-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroLivros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=13)),
                ("edicao", models.CharField(max_length=255)),
                ("editora", models.CharField(max_length=255)),
                ("ano_publicacao", models.TextField()),
                ("preco_capa", models.FloatField()),
                ("categoria", models.CharField(max_length=255)),
                ("autores", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ControleEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_livros", models.IntegerField()),
                ("controle_estoquecol", models.IntegerField()),
                ("data_entrada_livro", models.DateField()),
                ("data_saida_livro", models.DateField()),
                (
                    "cadastro_livros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.cadastrolivros",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CadastroAutores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("nacionalidade", models.CharField(max_length=255)),
                ("biografia", models.CharField(max_length=1000)),
                (
                    "cadastro_livros",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.cadastrolivros",
                    ),
                ),
            ],
        ),
    ]
