# Generated by Django 4.2.19 on 2025-02-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrolivros",
            name="ano_publicacao",
            field=models.TextField(max_length=4),
        ),
    ]
